some improvements to backend test
zestyai/engineering-test-backend pull request #8
Opened 2021-12-20 22:19 UTC by amerski99

- more background info to explain goals of the test
- lots of fixes and cleanup to api specifications (including, but not limited to fixing all places that incorrectly describe buildings as arrays)
- FAQ section
- upgrade postgres version in docker-compose

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +This test is an opportunity for you to demonstrate your skills and comfort with developing back-end services as well addressing difficult unknown problems.
```suggestion
This test is an opportunity for you to demonstrate your skills and comfort with developing back-end services as well as addressing difficult unknown problems.
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +The content of this test is designed to cover challenges that are very similar to real ones you would encounter working at zesty.ai (rather than random
```suggestion
The content of this test is designed to cover challenges that are very similar to real ones you would encounter working at Zesty.ai (rather than
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +* **Display Plus:** An alternative version of first API endpoint (**Display**) to also overlay the geocode (as a marker - such as a small circle or triangle), parcel, and/or building (`geocode_geo`,
```suggestion
* **Display Plus:** An alternative version of the first API endpoint (**Display**) to also overlay the geocode (as a marker - such as a small circle or triangle), parcel, and/or building (`geocode_geo`, `parcel_geo`, and `building_geo` fields in the database, respectively) on the image. You can optionally add parameters for the color of each overlay, or use a default for each. 
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +Your code should be in Python 3.x.  If you want to run/test your project locally, you of course can, but ultimately, your API should be made available as a docker image.
```suggestion
Your code should be in Python 3.x. If you want to run/test your project locally, you of course can, but ultimately, your API should be made available as a Docker image.
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +You will need to install docker and [`docker-compose`](https://docs.docker.com/compose/install/) to run the example database.
```suggestion
You will need to install Docker to run the example database.
```

I think docker-compose comes bundled with regular Docker now and there's no need to install it separately anymore, so long that you replace `docker-compose` commands by `docker compose`.

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +Your code should be in Python 3.x.  If you want to run/test your project locally, you of course can, but ultimately, your API should be made available as a docker image.
I would use "Docker" when talking about the general product, and only use lowercase "docker" when talking about the CLI utility

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +Note, that this includes specification for all endpoints.  You may ignore the ones for features that you do not implement.
```suggestion
Note that this includes the specification for all endpoints. You may ignore the ones for features that you do not implement.
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +JSON object with following properties
```suggestion
JSON object with the following properties
```

2021-12-21 03:44 UTC, pascal-giguere commented on README.md
> +JSON array with objects containing at least the following fields (you may include more if you think they be helpful)
```suggestion
JSON array with objects containing at least the following fields (you may include more if you think they would be helpful)
```

2021-12-22 17:46 UTC, pascal-giguere commented on README.md
>  `example: POST localhost:1235/find`
Since the endpoint's implementation is getting updated to be more RESTful (returns the entire resources, not just its ID), we might want to update the endpoint to be more RESTful as well.

```suggestion
`example: GET localhost:1235/property`
```

2021-12-22 17:58 UTC, pascal-giguere commented on README.md
> -  * buildings areas (array, meters squared)
Regarding the array to no array change:

I do think it's an improvement, and the other versions of the test (front-end and full-stack) also still mention "array". We should change it everywhere for consistency.

That being said, it's also not a big deal to have a spec that doesn't fully make sense (yet). One could assume the array is because we want to be future-proof and support multiple buildings in the future. In fact, that's what we're doing in our real API with the /zproperty endpoint: We return an array even though the array size will always be 1. 

So no big deal that the test was like that as well, but I'd still change it to reduce potential confusion.

2021-12-22 18:01 UTC, pascal-giguere commented on README.md
> +you need to create a deliverable you are proud of.
I like this answer

2021-12-22 18:05 UTC, pascal-giguere commented on README.md
> +not be wasted, as all of the technologies on this test are used frequently at zesty.ai.  It is not required that you complete all features on the test -
I don't know if the "time would not be wasted" argument is convincing from the candidate's perspective. Time would definitely not be wasted from Zesty's perspective, given that this essentially serves as training, but the thing is that it's unpaid training. So perhaps a candidate could argue that they should get paid for time spent on the test if we talk about it like it's training for the real job?

(I don't think we should actually people to take the test, I just think the wording here could imply that)

2021-12-22 18:07 UTC, pascal-giguere commented on README.md
> +questions before you start the test.
Great addition

2021-12-22 23:46 UTC, WojoSite approved these changes

2021-12-23 00:41 UTC, vasiliszai commented on README.md
> +the kind of problems you might face on our team.
kind of problems you might face working on our stack.

2021-12-23 00:47 UTC, vasiliszai commented on README.md
> +  "distance": 500
Distance is not part of the geojson "spec", thus the `x-` prefix. I think we should leave it there.

2021-12-23 00:49 UTC, vasiliszai commented on README.md
> +who completed only 50% of it.**
We should remove this "promise". We definitely don't want to be promising anything.

2021-12-23 00:50 UTC, vasiliszai commented on README.md
> +On the flip-side, if this test feels burdensome, it's very likely you would not enjoy the work at zesty.ai.
We should remove this too. I don't think we are familiar enough with the candidates to make "Andy" comments ;)

2021-12-23 00:53 UTC, vasiliszai requested changes
See individual comments.

2021-12-23 01:03 UTC, amerski99 commented on README.md
> +  "distance": 500
I intentionally made geojson a separate field so that we didn't have this problem. Otherwise they have to do a "feature" type, which seems overkill for a point

2021-12-23 01:04 UTC, amerski99 commented on README.md
> +On the flip-side, if this test feels burdensome, it's very likely you would not enjoy the work at zesty.ai.
Which part in particular?

2021-12-24 01:04 UTC, vasiliszai commented on README.md
> +On the flip-side, if this test feels burdensome, it's very likely you would not enjoy the work at zesty.ai.
> On the flip-side, if this test feels burdensome, it's very likely you would not enjoy the work at zesty.ai.

this part. I think it's a little negative

2021-12-27 18:10 UTC, erenbaszai commented on README.md
> +The content of this test is designed to cover challenges that are very similar to real ones you would encounter working at zesty.ai (rather than random
I would take out `(rather than random abstract computer-science projects)`. This is redundant. Does not provide any useful information to candidate about this test.

2021-12-27 18:16 UTC, erenbaszai commented on README.md
> +This test is an opportunity for you to demonstrate your skills and comfort with developing back-end services as well addressing difficult unknown problems.
I would also avoid all second person pronouns (you, yours) and try to avoid all pronouns as much as possible. So this sentence would be `This test is an opportunity for you to demonstrate your skills and comfort` => `This test is an opportunity to demonstrate the skills and comfort`

2021-12-27 18:24 UTC, erenbaszai commented on README.md
>  ## Submission instructions
We could ask candidate to quote all his resources in the submission.

2021-12-27 18:30 UTC, erenbaszai commented on README.md
> +#### Ugh, this test is long. Why?
I would remove this section talking about why the test is long. Firstly never admit it is long. This may change the perception of the candidate.

2021-12-27 18:41 UTC, erenbaszai commented
Should we also request candidates to wrap docker image with k8s yaml files (make it deployable) as a bonus feature?

2022-01-06 21:28 UTC, erenbaszai commented on README.md
>  `example: POST localhost:1235/find`
leaving this as is, since in our stack this is very common pattern due to complexity of the input.

2022-01-06 21:36 UTC, erenbaszai approved these changes

2022-01-09 21:45 UTC, vasiliszai approved these changes

2022-01-10 18:50 UTC, pascal-giguere approved these changes

2022-01-10 20:21 UTC, merged